# Generated by Django 2.2 on 2020-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneTable', '0002_auto_20200312_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisoner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='prisoner',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
