# Generated by Django 2.2 on 2020-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneTable', '0004_auto_20200313_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='dislikes',
            field=models.ManyToManyField(related_name='prisoner_dislikes', to='appOneTable.Dungeon'),
        ),
    ]
