# Generated by Django 2.2 on 2020-03-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
